language: node_js
dist: trusty
node_js:
  - 7
sudo: required
addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - google-chrome --version
  - npm install -g npm@5.5.1
script:
  - npm run package